import json
import logging

import anthropic

import config
from models import Job, Profile

logger = logging.getLogger(__name__)

_client: anthropic.Anthropic | None = None

# Leon's AI stack — injected into every cover letter to tell the story
AI_STACK_BLURB = """\
- Built "Jobber": a Dockerized job search assistant that auto-scrapes job boards daily \
and uses the Claude API to rank and surface the best matches — that's how I found this role
- Run Claude Code on a home server and SSH in from my phone to code on the go
- Use Claude Code and GitHub Copilot professionally to ship faster and focus attention on system design
- Integrated AI-generated workout plans into a personal fitness app (React Native + Flask)\
"""


def _build_prompt(job: Job, profile: Profile) -> str:
    profile_section = (
        profile.resume_md.strip()
        if (profile and profile.resume_md)
        else (
            "Software Engineer with 4+ years experience across PHP, Python, Node.js, React, "
            "TypeScript, AWS, Docker, PostgreSQL, MySQL. Currently at VoPay International "
            "(fintech/payments). Previously Full Stack Developer at New Zealand Exchange. "
            "BSc Computer Science, GPA 3.86/4. Based in Vancouver, BC."
        )
    )
    description = (job.description_raw or "")[:4000]
    salary_str = ""
    if job.salary_min or job.salary_max:
        parts = []
        if job.salary_min:
            parts.append(f"${job.salary_min:,}")
        if job.salary_max:
            parts.append(f"${job.salary_max:,}")
        salary_str = f"Salary: {' – '.join(parts)} {job.salary_currency or 'CAD'}"

    return f"""You are helping Leon Menzies, a software engineer in Vancouver BC, write a tailored job application.

## Leon's Profile
{profile_section}

## Leon's AI Setup (use this in the cover letter)
{AI_STACK_BLURB}

## Target Role
Title: {job.title}
Company: {job.company}
Location: {job.location or "Vancouver, BC"}
{salary_str}
Description:
{description}

## Instructions
Generate two things:

### 1. Resume bullets
3–5 bullet points tailored specifically to this role. Lead with impact and quantify where possible. \
Pick the most relevant experiences from Leon's background.

### 2. Cover letter
3–4 paragraphs. Requirements:
- Open with a strong hook specific to this company/role — no generic "I am writing to apply" openers
- Highlight 2–3 most relevant experiences that directly address what this company needs
- Include one honest, confident paragraph explaining that this letter was generated by Claude — \
frame it as a feature: Leon actively builds with AI, uses it daily, and this is a live demonstration. \
Reference Jobber (the job search tool he built), the home server SSH setup, and his professional use \
of Claude Code. Make it sound genuine and human, not like a disclaimer.
- Close with a direct call to action
- Tone: confident, direct, zero corporate fluff. Write like a real person who knows their worth.

Return ONLY valid JSON with no explanation outside it:
{{
  "resume_bullets": ["bullet 1", "bullet 2", "bullet 3"],
  "cover_letter": "full cover letter text — use \\n\\n for paragraph breaks",
  "subject_line": "Suggested email subject line"
}}
"""


def generate_application(job: Job, profile: Profile | None) -> dict:
    global _client
    if _client is None:
        _client = anthropic.Anthropic(api_key=config.CLAUDE_API_KEY)

    prompt = _build_prompt(job, profile or Profile())
    response = _client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}],
    )

    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    return json.loads(raw)
